import { PropsWithChildren } from "react"
import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
}

export default function RootAdminLayout({ children }: PropsWithChildren) {
    return <div className="size-full min-h-screen">{children}</div>
}
