import { PropsWithChildren } from "react"
import type { Metadata } from "next"
import { TooltipProvider } from "@shared/ui/tooltip"

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
}

export default function RootAdminLayout({ children }: PropsWithChildren) {
    return <>{children}</>
}
