import type { Metadata } from "next"
import { PropsWithChildren } from "react"

import "@/shared/config/styles/index.css"

export const metadata: Metadata = {
    title: "Client",
    description: "Generated by create next app",
}

export default function RootClientLayout({ children }: PropsWithChildren) {
    return <div className="size-full min-h-screen">{children}</div>
}
