import type { Metadata } from "next"
import { PropsWithChildren } from "react"

import "@/shared/config/styles/index.css"

export const metadata: Metadata = {
    title: {
        default: "App",
        template: "App | %s",
    },
    description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="flex min-h-full flex-col" suppressHydrationWarning>
                {children}
            </body>
        </html>
    )
}
