import type { Metadata } from "next"
import { ReactNode } from "react"

/* Fonts */
import { Nunito } from "next/font/google"

import "../config/styles/index.css"
import { cn } from "@/lib"

const nunito = Nunito({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-nunito",
})

export const metadata: Metadata = {
    title: {
        default: "App",
        template: "App | %s",
    },
    description: "Generated by create next app",
}

interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body suppressHydrationWarning className={cn(nunito.className)}>
                <div className="mx-auto w-full max-w-480">{children}</div>
            </body>
        </html>
    )
}
