import type { Metadata } from "next"
import { PropsWithChildren } from "react"

import "@/shared/config/styles/index.css"
import { Geist } from "next/font/google"
import { cn } from "@shared/lib"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
    title: {
        default: "App",
        template: "App | %s",
    },
    description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
            <body className="flex min-h-full flex-col" suppressHydrationWarning>
                {children}
            </body>
        </html>
    )
}
